name: .NET

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore DeveloperGeniue.sln
      - name: Build
        run: dotnet build DeveloperGeniue.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test DeveloperGeniue.sln --configuration Release --no-build
